// Core product and content data for D3: Digital Data Dimensions (static source of truth)
// TimeTech solutions, serving GCC enterprises since 2010

export const SOLUTIONS = [
  {
    slug: 'timetech-application',
    num: '01',
    title: 'TimeTech Platform',
    desc: 'Complete cloud-based workforce intelligence platform: time attendance, HRMS, payroll, visitor management, mobile app and employee self-service, built for GCC enterprises.',
    tags: ['Biometric', 'Cloud', 'Multi-company', 'iOS & Android'],
    icon: 'clock',
  },
  {
    slug: 'time-attendance-system',
    num: '02',
    title: 'Time Attendance: Standard',
    desc: 'Biometric fingerprint, face recognition and card-based attendance with real-time processing, auto-shift picking, LMRA-compliant payroll export and unlimited sites.',
    tags: ['Biometric', 'LMRA Ready', 'Auto Shift', 'Mobile App'],
    icon: 'clock',
  },
  {
    slug: 'time-attendance-enterprise',
    num: '02b',
    title: 'Time Attendance: Enterprise',
    desc: 'No.1 TimeTech. Multi-site, multi-company enterprise attendance for unlimited locations, with project manhour tracking, geo-fenced mobile app and full self-service portal.',
    tags: ['Multi-Site', 'Mobile App', 'Geo-Fencing', 'Project Manhours', 'Self-Service'],
    icon: 'clock',
  },
  {
    slug: 'hr-payroll-software',
    num: '03',
    title: 'HR & Payroll Software',
    desc: 'TimeTech professional HRMS and Payroll for the Gulf Region. Multi-company, multi-currency, bi-lingual, flexible and cost effective. Covers the complete employee lifecycle.',
    tags: ['Multi-Company', 'GOSI Ready', 'WPS Export', 'Self-Service', 'Mobile App', 'Appraisal'],
    icon: 'users',
  },
  {
    slug: 'visitor-management',
    num: '04',
    title: 'Visitor Management System',
    desc: 'Professional and advanced online visitor management: reception kiosk, pre-registration, access card issuance, door assignment and full audit trail.',
    tags: ['Access Card Integration', 'Pre-Registration', 'Audit Trail'],
    icon: 'users',
  },
  {
    slug: 'queue-management-system',
    num: '05',
    title: 'Queue Management System',
    desc: 'Wired and wireless kiosk-based queue management with audio announcements, multi-service categories, live analytics and supervisor reporting for ministries and enterprises.',
    tags: ['Kiosk', 'Wired & Wireless', 'Analytics'],
    icon: 'users',
  },
  {
    slug: 'digital-signage',
    num: '06',
    title: 'Digital Signage & Displays',
    desc: 'LED, LCD and vertical signage displays from 42" with 4K support, 24/7 operation, centralized CMS, Android OS and optional touch screen for indoor and outdoor deployments.',
    tags: ['4K LED', 'Remote CMS', '24/7 Operation', 'eBook'],
    icon: 'monitor',
  },
  {
    slug: 'rfid-asset-tracking',
    num: '07',
    title: 'RFID & Asset Tracking',
    desc: 'Active and passive RFID tracking for assets, documents and warehouse inventory across multiple buildings, departments and warehouses with mobile handheld terminal support.',
    tags: ['Active RFID', 'Warehouse WMS', 'Document Tracking', 'Mobile'],
    icon: 'layers',
  },
  {
    slug: 'access-control-system',
    num: '08',
    title: 'IP CCTV & Access Control',
    desc: 'Enterprise-grade IP surveillance cameras, biometric access controllers and proximity card systems integrated with centralized management software for GCC security compliance.',
    tags: ['IP Camera', 'Face Recognition', 'NFC / Proximity', 'Biometric'],
    icon: 'shield',
  },
  {
    slug: 'erp-retail-management',
    num: '09',
    title: 'ERP & Retail Management',
    desc: 'Full ERP covering procurement, inventory, sales, financial accounting, payroll, restaurant management and electronic shelf labels. Multi-company, multi-currency, multi-branch.',
    tags: ['Multi-Company', 'ESL', 'Inventory', 'Retail POS'],
    icon: 'briefcase',
  },
  {
    slug: 'consultancy',
    num: '10',
    title: 'IT Consultancy',
    desc: 'D3 provides outsourced IT staffing and consultancy for short-term projects, system implementations and ongoing managed service engagements across Bahrain and the GCC.',
    tags: ['Outsourced IT', 'ICT Planning', 'Managed Services', 'CISCO Certified'],
    icon: 'briefcase',
  },
];

export const INDUSTRIES = [
  {
    slug: 'government',
    title: 'Government',
    desc: 'Labour law compliance, LMRA integration, biometric attendance for civil service and ministry-grade physical security.',
    icon: 'building',
    challenges: [
      { title: 'LMRA & Labour Compliance', desc: 'Full alignment with Bahrain Labour Market Regulatory Authority requirements and GCC labour law.' },
      { title: 'Large Distributed Workforce', desc: 'Managing thousands of employees across multiple ministries and government departments.' },
      { title: 'Ministry-Grade Security', desc: 'Biometric access control, IP CCTV and visitor management for sensitive government facilities.' },
    ],
  },
  {
    slug: 'healthcare',
    title: 'Healthcare',
    desc: '24/7 shift scheduling, medical credential tracking, queue management for outpatient services and RFID equipment tracking.',
    icon: 'heart',
    challenges: [
      { title: '24/7 Shift Management', desc: 'Complex rotating schedules for doctors, nurses and support staff with Ramadan and special shift support.' },
      { title: 'Patient Queue Optimisation', desc: 'Reducing waiting times in outpatient clinics and emergency departments with intelligent queue kiosks.' },
      { title: 'Credential & Document Tracking', desc: 'Maintaining up-to-date certifications, licenses and compliance documents with automated reminders.' },
    ],
  },
  {
    slug: 'banking',
    title: 'Banking & Finance',
    desc: 'Audit-compliant attendance records, secure biometric access, visitor screening and SOX-ready payroll reporting.',
    icon: 'credit-card',
    challenges: [
      { title: 'Regulatory Compliance', desc: 'SOX, Central Bank of Bahrain and internal audit reporting requirements met with full data integrity.' },
      { title: 'Visitor & Branch Security', desc: 'Comprehensive visitor management and biometric door access across all branch locations.' },
      { title: 'Payroll Accuracy', desc: 'Zero-error payroll with direct WPS integration, GOSI calculations and multi-currency support.' },
    ],
  },
  {
    slug: 'retail',
    title: 'Retail',
    desc: 'ERP, electronic shelf labels, real-time inventory control, workforce scheduling and POS integration for multi-location retailers.',
    icon: 'shopping-bag',
    challenges: [
      { title: 'Real-Time Inventory', desc: 'Live stock visibility across all locations with RFID and barcode scanning.' },
      { title: 'Electronic Shelf Labels', desc: 'Instant price updates across all shelves, eliminating manual repricing and pricing errors.' },
      { title: 'Peak Workforce Scheduling', desc: 'Automated staff rostering based on footfall patterns and sales data.' },
    ],
  },
  {
    slug: 'logistics',
    title: 'Logistics',
    desc: 'RFID warehouse management, asset tracking with handheld terminals, IP fleet surveillance and distributed workforce management.',
    icon: 'truck',
    challenges: [
      { title: 'Warehouse & Asset Visibility', desc: 'RFID tracking across multiple warehouses with real-time stock levels and cycle counts.' },
      { title: 'Fleet & Yard Security', desc: 'IP CCTV monitoring for loading bays, vehicles and high-value cargo areas.' },
      { title: 'Distributed Workforce', desc: 'Managing shift workers across multiple depots and sites with mobile attendance.' },
    ],
  },
];

export const CASE_STUDIES = [
  {
    slug: 'ministry-of-interior-attendance',
    clientName: 'Government Ministry',
    clientType: 'Government',
    problem: 'No unified attendance system across dozens of departments. Manual registers, buddy-punching and no LMRA-compliant reporting.',
    solution: 'Deployed TimeTech biometric attendance terminals, central dashboard and auto LMRA report generation across all departments.',
    result: 'Eliminated manual attendance processing, achieved LMRA compliance and dramatically reduced payroll discrepancies.',
  },
  {
    slug: 'bank-of-bahrain-kuwait-hrms',
    clientName: 'GCC Commercial Bank',
    clientType: 'Banking',
    problem: 'Legacy HR system with no employee self-service, creating high admin overhead and slow payroll approvals.',
    solution: 'Full TimeTech HRMS deployment including employee self-service portal, mobile app, payroll engine and appraisal module.',
    result: 'Significant reduction in HR admin workload; employees now manage leave, overtime and payslips independently.',
  },
  {
    slug: 'gulf-air-queue-management',
    clientName: 'Regional Transport Hub',
    clientType: 'Government',
    problem: 'Long service queues causing customer dissatisfaction and staff overload across multiple service counters.',
    solution: 'TimeTech Queue Management with kiosks, digital display screens, WhatsApp virtual queue and real-time service analytics.',
    result: 'Substantially reduced average wait times and measurably improved citizen satisfaction scores.',
  },
  {
    slug: 'bahrain-airport-cctv',
    clientName: 'International Airport',
    clientType: 'Government',
    problem: 'Fragmented CCTV coverage, no centralised access control, multiple security blind spots across terminals.',
    solution: 'Full IP CCTV deployment and biometric access control across all terminal checkpoints with centralised management.',
    result: 'Achieved full security compliance, eliminated blind spots and reduced incident response time significantly.',
  },
  {
    slug: 'alba-rfid-assets',
    clientName: 'Industrial Manufacturer',
    clientType: 'Industrial',
    problem: 'Thousands of high-value industrial assets with no reliable tracking, leading to frequent loss and audit failures.',
    solution: 'RFID fixed asset tracking with handheld mobile terminals and centralised asset management software.',
    result: 'Near-zero unaccounted asset loss, passed external audits and improved asset utilisation across all sites.',
  },
  {
    slug: 'jawad-business-erp',
    clientName: 'Multi-location Retail Group',
    clientType: 'Retail',
    problem: 'Disconnected POS, inventory and HR systems across a large branch network causing reconciliation delays.',
    solution: 'Unified D3 ERP with electronic shelf labels, real-time inventory and integrated payroll management.',
    result: 'Price updates now take seconds instead of days; inventory errors reduced to near zero across all branches.',
  },
];

export const CLIENTS = {
  government: [
    'Bahrain Bourse',
    'Bahrain Chamber of Commerce and Industry (BCCI)',
    'Bahrain Institute for Political Development (BIPD)',
    'BIX – Bahrain Internet Exchange',
    'Civil Service Bureau (CSB)',
    'Central Bank of Bahrain (CBB)',
    'Isa Cultural Centre',
    'Labour Market Regulatory Authority (LMRA)',
    'Ministry of Cabinet Affairs & Prime Minister Office',
    'Ministry of Labour',
    'NSSA - National Space Science Agency',
    'Ministry of Interior – Customs Affairs',
    'Ministry of Islamic Affairs',
    'Northern Area Municipality',
    'Real Estate Regulatory Authority (RERA)',
    'Royal Humanitarian Foundation (RHF)',
    'Survey & Land Registration Bureau (SLRB)',
    'University of Bahrain',
    'Urban Planning Development Authority',
  ],
  private: [
    'Ahmed Zayani & Sons',
    'Ahmed Mansoor Al Ali Co',
    'AJM Kooheji Group B.S.C',
    'Al Iman School',
    'Al Hilal Hospital',
    'Al Salam Bank',
    'Al Zayani Investment',
    'Al Zain Jewellery',
    'American Express (AMEX)',
    'Ansari Engineering Services S.P.C',
    'Arab Open University',
    'Arab Architects',
    'Arabian Printing & Publishing House',
    'Arabtec Construction L.L.C (Bahrain Airport)',
    'AVM Labs',
    'Bahrain Medical Center (BMC)',
    'Bahrain Ship Repairing & Engineering Company B.S.C (BASREC)',
    'Balexco',
    'Banz Trading & Contracting W.L.L.',
    'BIIECO',
    'Bin Faquee',
    'Body Works',
    'CHAPO (BRF)',
    'City School',
    'CTS Middle East Bahrain W.L.L.',
    'Dahlman Middle East',
    'DAN Medical Center',
    'Dar Al Khaleej (GDN)',
    'Eagle Hills (Marassi)',
    'Etisalcom',
    'General Poultry Company (GPC)',
    'Ghousoon Spa & Saloon',
    'GTS - Global Lift Services Bahrain',
    'Gulf Assist',
    'Gulf Closures',
    'Gulf House Engineering',
    'Harmony Music Gate',
    'Ibn Al-Nafees Hospital Co. BSC',
    'iMachines',
    'International Motor Trading Agency W.L.L',
    'Invita Claims Management Company B.S.C',
    'Jah Consultancy',
    'Jalal Ionics WLL - Aqua Cool',
    'Jas Group W.L.L.',
    'Katana Torii Japanese Cuisine',
    'Keypoint',
    'Kims Health Hospital',
    'Kingdom University',
    'Lanterns Restaurants Group',
    'Linnas Medical Center',
    'Maersk Kanoo Bahrain W.L.L',
    'Maskati Commercials & Services',
    'Mohamed Salahuddin Consulting Engineering Bureau (MSCEB)',
    'Mueller Middle East',
    'Nass Corporation',
    'National Finance Exchange (NAFEX)',
    'Novo Delizie And Mercato',
    'Panorama Contracting',
    'Racing Force Group',
    'Reckitt Benckiser Bahrain W.L.L',
    'Saudi Company for Environment',
    'Sika Gulf',
    'Talal Abu-Ghazaleh Global (BRF - Tag)',
    'The National Concrete Company W.L.L (N.C.C)',
    'Wave Infra Solution',
    'West Point',
    'Yaquby Stores',
    'Yateem Air Conditioning',
    'Yokogawa',
    'Zayani Otis Elevator Company',
  ],
  gcc: [
    'Doha Club',
    'KIA Motors - Qatar',
    'NetLink - Dubai',
    'Schuyler Security Technologies',
    'United Supplies - Dubai',
    'Workers Village - Abu Dhabi',
    'KIMS Health Hospital Group',
  ],
};

export const BLOG_POSTS = [
  {
    slug: 'top-5-benefits-biometric-attendance',
    title: 'Top 5 Benefits of Biometric Attendance Systems for GCC Enterprises',
    excerpt: 'Biometric attendance eliminates buddy-punching, reduces payroll errors and ensures full LMRA compliance. Here\'s why GCC enterprises are upgrading from legacy systems.',
    tags: ['Time Attendance', 'Biometric', 'LMRA'],
    publishedAt: '2025-03-15',
  },
  {
    slug: 'queue-management-government-sector',
    title: 'How Queue Management Systems Are Transforming Government Services in the GCC',
    excerpt: 'From ministries to municipal offices, TimeTech\'s intelligent queue management is cutting wait times and improving citizen satisfaction across Bahrain and the GCC.',
    tags: ['Queue Management', 'Government', 'GCC'],
    publishedAt: '2025-02-28',
  },
  {
    slug: 'rfid-asset-tracking-manufacturing',
    title: 'RFID Asset Tracking: A Complete Guide for GCC Manufacturing & Industrial Companies',
    excerpt: 'Everything you need to know about RFID asset tracking in GCC industrial environments, from hardware selection to warehouse management software integration.',
    tags: ['RFID', 'Asset Tracking', 'Warehouse'],
    publishedAt: '2025-02-10',
  },
  {
    slug: 'choosing-hr-software-bahrain',
    title: 'How to Choose the Right HRMS for Your GCC Business in 2025',
    excerpt: 'A practical guide to evaluating HRMS platforms for GCC businesses, covering LMRA compliance, WPS payroll, Arabic support, GOSI integration and mobile capabilities.',
    tags: ['HRMS', 'Payroll', 'Bahrain', 'GCC'],
    publishedAt: '2025-01-20',
  },
];
