// Core product and content data for D3: Digital Data Dimensions (static source of truth)
// All content verified against dthree.co — do not add features or claims not on the original site.

export const SOLUTIONS = [
  {
    slug: 'time-attendance-system',
    num: '01',
    title: 'Time Attendance: Standard',
    desc: 'Time Attendance System for Bahrain SMEs — TimeTech biometric fingerprint, face recognition and card-based attendance with LMRA-compliant payroll export and unlimited sites.',
    tags: ['Biometric', 'LMRA Ready', 'Auto Shift', 'Mobile App'],
    icon: 'clock',
  },
  {
    slug: 'time-attendance-enterprise',
    num: '02',
    title: 'Time Attendance: Enterprise',
    desc: 'Enterprise Time Attendance for multi-site GCC organisations — TimeTech multi-company attendance with geo-fenced mobile app, project manhour tracking and self-service.',
    tags: ['Multi-Site', 'Mobile App', 'Geo-Fencing', 'Project Manhours', 'Self-Service'],
    icon: 'clock',
  },
  {
    slug: 'hr-payroll-software',
    num: '03',
    title: 'HRMS',
    desc: 'HRMS Bahrain — TimeTech professional HRMS and Payroll for the Gulf Region. Multi-company, WPS and GOSI ready, bilingual, covering the complete employee lifecycle.',
    tags: ['Multi-Company', 'GOSI Ready', 'WPS Export', 'Self-Service', 'Mobile App', 'Appraisal'],
    icon: 'users',
  },
  {
    slug: 'visitor-management',
    num: '04',
    title: 'Visitor Management System',
    desc: 'Visitor Management System Bahrain — TimeTech reception kiosk, pre-registration, access card issuance, door assignment and full audit trail for offices and government buildings.',
    tags: ['Access Card Integration', 'Pre-Registration', 'Audit Trail'],
    icon: 'users',
  },
  {
    slug: 'queue-management-system',
    num: '05',
    title: 'Queue Management System',
    desc: 'Queue Management System Bahrain — TimeTech wired and wireless kiosks with audio announcements, LED displays and live analytics for ministries and hospitals.',
    tags: ['Kiosk', 'Wired & Wireless', 'Audio Announcements', 'Analytics'],
    icon: 'users',
  },
  {
    slug: 'digital-signage',
    num: '06',
    title: 'Digital Signage & Displays',
    desc: 'Digital Signage Bahrain — TimeTech 4K LED and LCD displays with centralised CMS, 24/7 operation and indoor/outdoor deployment for retail and corporate spaces.',
    tags: ['4K LED', 'Remote CMS', '24/7 Operation', 'eBook'],
    icon: 'monitor',
  },
  {
    slug: 'rfid-asset-tracking',
    num: '07',
    title: 'RFID & Asset Tracking',
    desc: 'RFID Asset Tracking Bahrain — TimeTech active and passive RFID for warehouse inventory, documents and assets across multiple buildings with handheld audits.',
    tags: ['Active RFID', 'Warehouse WMS', 'Document Tracking', 'Mobile'],
    icon: 'layers',
  },
  {
    slug: 'access-control-system',
    num: '08',
    title: 'IP CCTV & Access Control',
    desc: 'Access Control System Bahrain — TimeTech IP CCTV, biometric door access and NFC proximity cards with centralised security management for GCC enterprises.',
    tags: ['IP Camera', 'Face Recognition', 'NFC / Proximity', 'Biometric'],
    icon: 'shield',
  },
  {
    slug: 'erp-retail-management',
    num: '09',
    title: 'ERP & Retail Management',
    desc: 'ERP Software Bahrain — TimeTech full ERP for retail and enterprise: procurement, inventory, POS, electronic shelf labels and multi-branch financial accounting.',
    tags: ['Multi-Company', 'ESL', 'Inventory', 'Van Sales'],
    icon: 'briefcase',
  },
  {
    slug: 'consultancy',
    num: '10',
    title: 'IT Consultancy',
    desc: 'IT Consultancy Bahrain — outsourced IT staffing, managed services and ICT planning for short-term projects and ongoing engagements across Bahrain and the GCC.',
    tags: ['Outsourced IT', 'ICT Planning', 'Managed Services', 'CISCO Certified'],
    icon: 'briefcase',
  },
];

export const INDUSTRIES = [
  {
    slug: 'government',
    title: 'Government',
    desc: 'Labour law compliance, LMRA integration, biometric attendance for civil service and ministry-grade physical security.',
    icon: 'building',
    challenges: [
      {
        title: 'LMRA & Labour Compliance',
        desc: 'Full alignment with Bahrain Labour Market Regulatory Authority requirements and Civil Service Bureau rules.',
      },
      {
        title: 'Large Distributed Workforce',
        desc: 'Managing thousands of employees across multiple ministries and government departments with centralised reporting.',
      },
      {
        title: 'Ministry-Grade Security',
        desc: 'Biometric access control, IP CCTV and visitor management for government facilities.',
      },
    ],
  },
  {
    slug: 'healthcare',
    title: 'Healthcare',
    desc: '24/7 shift scheduling, medical credential tracking, queue management for outpatient services and RFID equipment tracking.',
    icon: 'heart',
    challenges: [
      {
        title: '24/7 Shift Management',
        desc: 'Complex rotating schedules for doctors, nurses and support staff with Ramadan and special shift support.',
      },
      {
        title: 'Patient Queue Management',
        desc: 'Reducing waiting times in outpatient clinics and hospital departments with intelligent queue kiosks.',
      },
      {
        title: 'Credential & Document Tracking',
        desc: 'Maintaining up-to-date certifications, licenses and compliance documents with automated expiry reminders.',
      },
    ],
  },
  {
    slug: 'retail',
    title: 'Retail',
    desc: 'ERP, electronic shelf labels, real-time inventory control, workforce management and van sales for multi-location retailers.',
    icon: 'shopping-bag',
    challenges: [
      {
        title: 'Real-Time Inventory',
        desc: 'Live stock visibility across all locations with RFID and barcode scanning.',
      },
      {
        title: 'Electronic Shelf Labels',
        desc: 'Instant price updates across all shelves, eliminating manual repricing and pricing errors.',
      },
      {
        title: 'Workforce Management',
        desc: 'Shift scheduling and attendance management for multi-location retail staff with real-time reporting.',
      },
    ],
  },
  {
    slug: 'logistics',
    title: 'Logistics',
    desc: 'RFID warehouse management, asset tracking with handheld terminals, IP surveillance and distributed workforce management.',
    icon: 'truck',
    challenges: [
      {
        title: 'Warehouse & Asset Visibility',
        desc: 'RFID tracking across multiple warehouses with real-time stock levels and cycle counts.',
      },
      {
        title: 'Site Security',
        desc: 'IP CCTV monitoring for loading bays and warehouse areas.',
      },
      {
        title: 'Distributed Workforce',
        desc: 'Managing shift workers across multiple depots and sites with mobile attendance.',
      },
    ],
  },
];

// Real client projects — sourced verbatim from dthree.co homepage.
// These are the only verified project descriptions D3 publishes publicly.
// Do NOT add fabricated outcomes or made-up metrics.
export const CASE_STUDIES = [
  {
    slug: 'survey-land-registration-bureau',
    clientName: 'Survey & Land Registration Bureau',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Upgrade of Personnel, Leave, Employee Self Service and Time Attendance modules, including integration with Civil Service Bureau.',
  },
  {
    slug: 'labour-market-regulatory-authority',
    clientName: 'Labour Market Regulatory Authority (LMRA)',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 350 staff with 17 devices installed. Email notifications implemented, CSB Rules applied and historical data migrated to the new system.',
  },
  {
    slug: 'ministry-of-foreign-affairs',
    clientName: 'Ministry of Foreign Affairs',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance devices deployed across 40 Bahrain embassies worldwide with centralised reporting. System configured to calculate and mark attendance using the local time of each embassy.',
  },
  {
    slug: 'ministry-of-islamic-affairs',
    clientName: 'Ministry of Islamic Affairs',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 200 staff with online access. CSB Rules implemented, SMS notifications for out-time, software deployed on AWS.',
  },
  {
    slug: 'royal-humanitarian-foundation',
    clientName: 'Royal Humanitarian Foundation',
    clientType: 'Government',
    sector: 'Government',
    solution: 'New comprehensive HRMS system including HR, Personnel, Payroll, Time Attendance, Appraisal, Training, Self-Service and email notification.',
  },
  {
    slug: 'bahrain-institute-political-development',
    clientName: 'Bahrain Institute for Political Development (BIPD)',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 70 staff with online access. CSB Rules implemented, employee email notifications for out-time, software deployed on AWS.',
  },
  {
    slug: 'university-of-bahrain',
    clientName: 'University of Bahrain',
    clientType: 'Education',
    sector: 'Government',
    solution: '42 time attendance devices installed and integrated with Oracle for 1,200 staff.',
  },
  {
    slug: 'muller-middle-east',
    clientName: 'Muller Middle East',
    clientType: 'Private',
    sector: 'Private Sector',
    solution: 'Comprehensive HRMS system including HR, Personnel, Payroll, Time Attendance, Appraisal, Planning & Recruitment, Budgeting, Training, Self-Service and email notification.',
  },
];

export const CLIENTS = {
  government: [
    'Bahrain Bourse',
    'Bahrain Chamber of Commerce and Industry (BCCI)',
    'Bahrain Institute for Political Development (BIPD)',
    'BIX – Bahrain Internet Exchange',
    'Civil Service Bureau (CSB)',
    'Isa Cultural Centre',
    'Labour Market Regulatory Authority (LMRA)',
    'Ministry of Cabinet Affairs & Prime Minister Office',
    'Ministry of Labour',
    'NSSA - National Space Science Agency',
    'Ministry of Interior – Customs Affairs',
    'Ministry of Islamic Affairs',
    'Northern Area Municipality',
    'Real Estate Regulatory Authority (RERA)',
    'Royal Humanitarian Foundation (RHF)',
    'Survey & Land Registration Bureau (SLRB)',
    'University of Bahrain',
    'Urban Planning Development Authority',
  ],
  private: [
    'Ahmed Zayani & Sons',
    'Ahmed Mansoor Al Ali Co',
    'AJM Kooheji Group B.S.C',
    'Al Iman School',
    'Al Hilal Hospital',
    'Al Zayani Investment',
    'Al Zain Jewellery',
    'Ansari Engineering Services S.P.C',
    'Arab Open University',
    'Arab Architects',
    'Arabian Printing & Publishing House',
    'Arabtec Construction L.L.C (Bahrain Airport)',
    'AVM Labs',
    'Bahrain Medical Center (BMC)',
    'Bahrain Ship Repairing & Engineering Company B.S.C (BASREC)',
    'Balexco',
    'Banz Trading & Contracting W.L.L.',
    'BIIECO',
    'Bin Faquee',
    'Body Works',
    'CHAPO (BRF)',
    'City School',
    'CTS Middle East Bahrain W.L.L.',
    'Dahlman Middle East',
    'DAN Medical Center',
    'Dar Al Khaleej (GDN)',
    'Eagle Hills (Marassi)',
    'Etisalcom',
    'General Poultry Company (GPC)',
    'Ghousoon Spa & Saloon',
    'GTS - Global Lift Services Bahrain',
    'Gulf Assist',
    'Gulf Closures',
    'Gulf House Engineering',
    'Harmony Music Gate',
    'Ibn Al-Nafees Hospital Co. BSC',
    'iMachines',
    'International Motor Trading Agency W.L.L',
    'Invita Claims Management Company B.S.C',
    'Jah Consultancy',
    'Jalal Ionics WLL - Aqua Cool',
    'Jas Group W.L.L.',
    'Katana Torii Japanese Cuisine',
    'Keypoint',
    'Kims Health Hospital',
    'Kingdom University',
    'Lanterns Restaurants Group',
    'Linnas Medical Center',
    'Maersk Kanoo Bahrain W.L.L',
    'Maskati Commercials & Services',
    'Mohamed Salahuddin Consulting Engineering Bureau (MSCEB)',
    'Mueller Middle East',
    'Nass Corporation',
    'Novo Delizie And Mercato',
    'Panorama Contracting',
    'Racing Force Group',
    'Reckitt Benckiser Bahrain W.L.L',
    'Saudi Company for Environment',
    'Sika Gulf',
    'Talal Abu-Ghazaleh Global (BRF - Tag)',
    'The National Concrete Company W.L.L (N.C.C)',
    'Wave Infra Solution',
    'West Point',
    'Yaquby Stores',
    'Yateem Air Conditioning',
    'Yokogawa',
    'Zayani Otis Elevator Company',
  ],
  gcc: [
    'Doha Club',
    'KIA Motors - Qatar',
    'NetLink - Dubai',
    'Schuyler Security Technologies',
    'United Supplies - Dubai',
    'Workers Village - Abu Dhabi',
    'KIMS Health Hospital Group',
  ],
};

/** Homepage trust marquee — logos from TimeTech partner slider (time-tech.co) */
export const TRUST_LOGOS: { name: string; logo: string }[] = [
  { name: 'Ibn Al-Nafees Hospital Bahrain', logo: '/images/logos/trust/ibnalnafees.png' },
  { name: 'Royal Humanitarian Foundation', logo: '/images/logos/trust/rhf.png' },
  { name: 'Bahrain Bourse', logo: '/images/logos/trust/bahrainbourse.png' },
  { name: 'Survey & Land Registration Bureau (SLRB)', logo: '/images/logos/trust/slrb.png' },
  { name: 'Sawa University', logo: '/images/logos/trust/sawa-university.png' },
  { name: 'King Hamad University Hospital', logo: '/images/logos/trust/khuh.png' },
  { name: 'Vanderlande', logo: '/images/logos/trust/vanderlande.png' },
  { name: 'Anbar University', logo: '/images/logos/trust/anbar-university.png' },
  { name: 'ASRY', logo: '/images/logos/trust/asry.png' },
  { name: 'Al Mouwasat Hospital', logo: '/images/logos/trust/mouwasat.png' },
  { name: 'Nass Corporation', logo: '/images/logos/trust/nass.png' },
  { name: 'BSA', logo: '/images/logos/trust/bsa.png' },
  { name: 'Arab Open University', logo: '/images/logos/trust/aou.png' },
];

export const BLOG_POSTS = [
  {
    slug: 'biometric-attendance-system-bahrain',
    title: 'Biometric Attendance System in Bahrain: The Complete Buying Guide',
    seoTitle: 'Biometric Attendance System in Bahrain | Fingerprint & Face Recognition | D3',
    excerpt: 'Compare biometric attendance systems in Bahrain — fingerprint, face recognition and card-based. See how D3\'s TimeTech-powered platform cuts payroll errors and stays LMRA-compliant.',
    tags: ['Time Attendance System Bahrain', 'Biometric Attendance', 'Face Recognition Attendance', 'Fingerprint Attendance'],
    publishedAt: '2026-07-01',
  },
  {
    slug: 'hrms-payroll-software-bahrain-guide',
    title: 'HRMS & Payroll Software in Bahrain: What to Look for Before You Buy',
    seoTitle: 'HRMS & Payroll Software Bahrain | Multi-Company Cloud HR Platform | D3',
    excerpt: 'How to choose HRMS and payroll software in Bahrain — WPS export, GOSI integration, multi-company support. A practical buying guide for GCC HR teams.',
    tags: ['HRMS Bahrain', 'Payroll Software Bahrain', 'WPS Payroll', 'GOSI Payroll'],
    publishedAt: '2026-07-05',
  },
  {
    slug: 'lmra-compliance-wps-payroll-bahrain',
    title: 'LMRA Compliance and WPS Payroll in Bahrain: What Employers Need to Know',
    seoTitle: 'LMRA Compliance & WPS Payroll in Bahrain: Employer Guide | D3',
    excerpt: 'What LMRA compliance and WPS payroll actually require from Bahrain employers, and how the right HR software keeps you compliant automatically.',
    tags: ['LMRA Compliance', 'WPS Payroll', 'GOSI Payroll', 'Civil Service Bureau'],
    publishedAt: '2026-07-08',
  },
  {
    slug: 'queue-management-system-bahrain',
    title: 'Queue Management Systems for Government and Healthcare in Bahrain',
    seoTitle: 'Queue Management System Bahrain | Government & Healthcare Kiosks | D3',
    excerpt: 'How queue management systems reduce wait times for ministries, hospitals, and enterprise service counters in Bahrain — kiosks, displays, and live analytics.',
    tags: ['Queue Management System Bahrain', 'Hospital Queue Management', 'Ministry Software Solutions'],
    publishedAt: '2026-07-10',
  },
  {
    slug: 'rfid-asset-tracking-warehouse-management-bahrain',
    title: 'RFID Asset Tracking and Warehouse Management: A Guide for GCC Enterprises',
    seoTitle: 'RFID Asset Tracking & Warehouse Management Bahrain | D3',
    excerpt: 'How RFID asset tracking and warehouse management systems improve inventory accuracy for GCC enterprises — active vs passive tags, use cases, and what to check before buying.',
    tags: ['RFID Asset Tracking Bahrain', 'Warehouse Management System', 'Asset Tracking System', 'RFID'],
    publishedAt: '2026-07-12',
  },
  {
    slug: 'gosi-contribution-calculation-bahrain',
    title: 'GOSI Contribution Calculation in Bahrain: A Practical Employer Guide',
    seoTitle: 'GOSI Contribution Calculation Bahrain | Social Insurance Guide | D3',
    excerpt: 'How GOSI contributions work in Bahrain — employer and employee rates, salary caps, and how payroll software automates social insurance calculations every pay cycle.',
    tags: ['GOSI', 'GOSI Bahrain', 'Social Insurance Bahrain'],
    publishedAt: '2026-07-15',
  },
  {
    slug: 'indemnity-calculation-bahrain',
    title: 'Indemnity Calculation in Bahrain: How End-of-Service Benefits Work',
    seoTitle: 'Indemnity Calculation Bahrain | End of Service Benefits Guide | D3',
    excerpt: 'A practical guide to indemnity calculation in Bahrain — how end-of-service benefits accrue, what affects the payout, and how HRMS software tracks balances automatically.',
    tags: ['Indemnity Calculator Bahrain', 'End of Service Benefits', 'LMRA'],
    publishedAt: '2026-07-18',
  },
  {
    slug: 'average-salary-bahrain',
    title: 'Average Salary in Bahrain: What Employers Should Know in 2026',
    seoTitle: 'Average Salary in Bahrain | Basic Salary & Payroll Guide | D3',
    excerpt: 'Understanding average salary benchmarks in Bahrain — how basic salary is structured, what counts toward GOSI and indemnity, and how payroll systems keep records accurate.',
    tags: ['Bahrain Salary', 'Basic Salary Bahrain'],
    publishedAt: '2026-07-20',
  },
  {
    slug: 'bahrain-labour-law-resignation-notice',
    title: 'Bahrain Labour Law Resignation Notice: Notice Period Rules for Employers',
    seoTitle: 'Bahrain Labour Law Resignation | Notice Period Guide | D3',
    excerpt: 'What Bahrain labour law requires for resignation notice periods — employee and employer obligations, termination types, and how HR software tracks notice and final settlement.',
    tags: ['Notice Period Bahrain', 'Employment Termination'],
    publishedAt: '2026-07-22',
  },
  {
    slug: 'salary-slip-format-bahrain',
    title: 'Salary Slip Format in Bahrain: What Every Payslip Must Include',
    seoTitle: 'Salary Slip Format Bahrain | Payslip Requirements | D3',
    excerpt: 'The essential fields for a compliant salary slip in Bahrain — basic salary, allowances, GOSI deductions, and how HRMS generates payslips automatically each cycle.',
    tags: ['Salary Slip Format', 'Payslip Bahrain'],
    publishedAt: '2026-07-24',
  },
  {
    slug: 'employment-contract-bahrain',
    title: 'Employment Contract in Bahrain: Key Clauses and LMRA Requirements',
    seoTitle: 'Employment Contract Bahrain | LMRA Contract Guide | D3',
    excerpt: 'What a Bahrain employment contract must cover — contract types, probation, salary terms, and how HRMS links contract data to payroll and LMRA reporting.',
    tags: ['Employment Contract Template', 'LMRA Contract'],
    publishedAt: '2026-07-26',
  },
  {
    slug: 'offer-letter-sample-bahrain',
    title: 'Offer Letter in Bahrain: What to Include Before the Employment Contract',
    seoTitle: 'Offer Letter Sample Bahrain | HR Templates Guide | D3',
    excerpt: 'How to structure an offer letter for Bahrain hires — salary breakdown, start date, benefits summary, and how HR templates flow into contract and payroll setup.',
    tags: ['Offer Letter Sample', 'HR Templates Bahrain'],
    publishedAt: '2026-07-28',
  },
  {
    slug: 'overtime-calculation-bahrain',
    title: 'Overtime Calculation in Bahrain: Rates, Rules and Payroll Integration',
    seoTitle: 'Overtime Calculation Bahrain | Labour Law Overtime Guide | D3',
    excerpt: 'How overtime pay is calculated under Bahrain labour law — standard rates, Ramadan rules, and how attendance-linked HRMS applies overtime automatically to payroll.',
    tags: ['Overtime Pay Bahrain', 'Labour Law Overtime'],
    publishedAt: '2026-07-30',
  },
  {
    slug: 'enterprise-time-attendance-multi-site-bahrain',
    title: 'Multi-Site Time Attendance for Enterprise & Government Groups in Bahrain',
    seoTitle: 'Multi-Site Time Attendance for Enterprise & Government Groups Bahrain | D3',
    excerpt: 'Managing attendance across multiple Bahrain branches or government sites? See how enterprise time attendance consolidates multi-site, multi-company workforce data into one dashboard.',
    tags: ['Enterprise Time Attendance', 'Multi-Company HRMS', 'GCC Time Attendance', 'Multi-Site Workforce Management'],
    publishedAt: '2026-08-05',
  },
  {
    slug: 'digital-signage-led-displays-bahrain',
    title: 'Digital Signage & LED Displays in Bahrain: Corporate, Retail & Government Use Cases',
    seoTitle: 'Digital Signage & LED Displays in Bahrain | Corporate, Retail & Government | D3',
    excerpt: 'Digital signage and LED display solutions for Bahrain retail, corporate lobbies and government buildings — content management, video walls and indoor/outdoor displays.',
    tags: ['Digital Signage Bahrain', 'LED Display Solutions', 'Video Wall Bahrain', 'Indoor Outdoor Signage'],
    publishedAt: '2026-08-12',
  },
  {
    slug: 'erp-retail-management-software-bahrain',
    title: 'ERP & Retail Management Software in Bahrain: Choosing the Right System',
    seoTitle: 'ERP & Retail Management Software in Bahrain | Inventory & Multi-Branch | D3',
    excerpt: 'Choosing ERP or retail management software in Bahrain? Compare inventory control, multi-branch stock visibility and POS integration before you buy.',
    tags: ['ERP Software Bahrain', 'Retail Management Software', 'Inventory Management Software'],
    publishedAt: '2026-08-19',
  },
  {
    slug: 'it-consultancy-managed-services-bahrain',
    title: 'IT Consultancy & Managed Services in Bahrain: What to Expect',
    seoTitle: 'IT Consultancy & Managed Services in Bahrain | D3',
    excerpt: 'What to expect from IT consultancy and managed services in Bahrain — infrastructure audits, digital transformation planning, and ongoing managed support.',
    tags: ['IT Consultancy Bahrain', 'Managed IT Services Bahrain', 'Digital Transformation Bahrain'],
    publishedAt: '2026-08-26',
  },
  {
    slug: 'visitor-management-system-bahrain-guide',
    title: 'Visitor Management System in Bahrain: Reception Kiosks, Pre-Registration and Access Cards',
    seoTitle: 'Visitor Management System Bahrain | Reception Kiosk & Pre-Registration | D3',
    excerpt: 'Digital visitor management for Bahrain offices and government buildings — reception kiosks, pre-registration, access card issuance and a full audit trail.',
    tags: ['Visitor Management System Bahrain', 'Digital Transformation Bahrain', 'Government IT Solutions'],
    publishedAt: '2026-08-27',
  },
  {
    slug: 'access-control-cctv-security-bahrain',
    title: 'Access Control and IP CCTV in Bahrain: Biometric Doors, NFC Cards and Central Monitoring',
    seoTitle: 'Access Control & IP CCTV in Bahrain | Biometric & NFC | D3',
    excerpt: 'How access control and IP CCTV work together for Bahrain offices and government sites — biometric doors, NFC proximity cards and centralised security management.',
    tags: ['Access Control System Bahrain', 'IP CCTV Bahrain', 'Biometric Access Control'],
    publishedAt: '2026-08-27',
  },
  {
    slug: 'top-5-benefits-biometric-attendance',
    title: 'Top 5 Benefits of Biometric Attendance Systems for GCC Enterprises',
    excerpt: 'Biometric attendance eliminates buddy-punching, reduces payroll errors and ensures full LMRA compliance. Here\'s why GCC enterprises are upgrading from legacy systems.',
    tags: ['GCC Enterprise Attendance', 'Buddy Punching Prevention', 'Payroll Accuracy'],
    publishedAt: '2026-02-15',
  },
  {
    slug: 'queue-management-government-sector',
    title: 'How Queue Management Systems Are Transforming Government Services in the GCC',
    excerpt: 'From ministries to municipal offices, TimeTech\'s queue management is cutting wait times and improving citizen satisfaction across Bahrain and the GCC.',
    tags: ['Citizen Service Delivery', 'WhatsApp Virtual Queue', 'Public Sector GCC'],
    publishedAt: '2026-03-01',
  },
  {
    slug: 'rfid-asset-tracking-manufacturing',
    title: 'RFID Asset Tracking: A Complete Guide for GCC Manufacturing & Industrial Companies',
    excerpt: 'Everything you need to know about RFID asset tracking in GCC industrial environments, from hardware selection to warehouse management software integration.',
    tags: ['Industrial RFID GCC', 'Manufacturing Asset Control', 'Handheld Cycle Counts'],
    publishedAt: '2026-03-15',
  },
  {
    slug: 'choosing-hr-software-bahrain',
    title: 'How to Choose the Right HRMS for Your GCC Business in 2026',
    excerpt: 'A practical guide to evaluating HRMS platforms for GCC businesses, covering LMRA compliance, WPS payroll, Arabic support, GOSI integration and mobile capabilities.',
    tags: ['HR Platform Evaluation', 'Arabic HR Software', 'Cloud vs On-Premise HR'],
    publishedAt: '2026-04-01',
  },
];

export function postsByNewest<T extends { publishedAt: string; slug?: string }>(posts: T[]) {
  return [...posts].sort((a, b) => {
    const byDate = b.publishedAt.localeCompare(a.publishedAt);
    if (byDate !== 0) return byDate;
    return (a.slug ?? '').localeCompare(b.slug ?? '');
  });
}

export function postsByOldest<T extends { publishedAt: string; slug?: string }>(posts: T[]) {
  return [...posts].sort((a, b) => {
    const byDate = a.publishedAt.localeCompare(b.publishedAt);
    if (byDate !== 0) return byDate;
    return (a.slug ?? '').localeCompare(b.slug ?? '');
  });
}
